# Basic
name: Hello World
description: 프로그래밍 학습용 블로그

# URL
url: " "
#baseurl: ""
permalink: /:year/:month/:day/:title.html

# Markdown
markdown: kramdown

lang: ko

# Navigation
nav:
 - name: "about"
   href: "/about"

 - name: "reference"
   href: "/ref"

 - name: "contact"
   href: "mailto:ivantheterrible@1530to1584.gov?You%20are%20ooold..."

# Sass
sass:
 style: :compressed

# Excerpt
excerpt_separator: <!-ex->

#Gems
gems: [jekyll-paginate]
paginate: 10
paginate_path: "/page:num/"

# Scopes
defaults:
 -
  scope:
   path: ""
   type: "pages"
  values:
   layout: "page"
 -
  scope:
   path: ""
   type: "posts"
  values:
   layout: "post"